### ISSUE TITLE
Can't add DataUnlocker script to Nextjs project

### ISSUE THREAD

**Issue by huongpanprices** [dataunlocker/save-analytics-from-content-blockers#26]
I tried to add DataUnlocker script to Nextjs project.

So instead of adding the script to `.html` file as your tutorial, it should be added in [_document.js](https://nextjs.org/docs/advanced-features/custom-document) of Nextjs project.

But I got a bunch of VSCode errors after added. Project also failed to start.

![Screen Shot 2021-02-24 at 11 18 32 PM](https://user-images.githubusercontent.com/70152463/109030810-b7a4df00-76f6-11eb-8023-908ec64e97e7.png)

I made an empty Nextjs project to add DataUnlocker script as an example: https://github.com/huongpanprices/dataunlocker-nextjs

It would be great to get your support. Thanks.

**Comment by ZitRos** [comment]
Hello! Thanks for filing the issue.

Please check https://github.com/vercel/next.js/issues/1413 and let me know whether it helped.

Thanks!

**Comment by huongpanprices** [comment]
@ZitRos I tried it but still couldn't resolve the issue

https://github.com/huongpanprices/dataunlocker-nextjs/commit/b9954747d49c050f3c8f25bbb6c34bcb82e1585b 

![Screen Shot 2021-02-24 at 11 39 04 PM](https://user-images.githubusercontent.com/70152463/109033805-998cae00-76f9-11eb-9dcc-e33b12fb22d7.png)

**Comment by ZitRos** [comment]
This happens because encoded script has `` ` `` symbol which needs to be escaped. I.e. you need to CTRL+R all the code and replace it with `` \` ``. You will also need to escape all other symbols and backslashes :)

It's better to use unencoded script in your case:

![image](https://user-images.githubusercontent.com/4989256/109034698-929d7580-76d0-11eb-857f-47bf1c73a3d6.png)

...or use [Continuous Integration](https://dataunlocker.com/faq/#script-ci) option in your CI pipeline which will properly modify the output HTML file made by NextJS.

**Comment by huongpanprices** [comment]
Works well now. Thanks for your help. :D

**Comment by ZitRos** [comment]
You're welcome! Happy DataUnlocking! :)
